[build]
  # Directorio donde se ejecuta el build
  base = "."
  # Comando para construir la aplicación
  command = "npm run build"
  # Directorio donde están los archivos estáticos generados
  publish = "dist"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"
  # Configuración de npm
  NPM_FLAGS = "--production=false"

# Configuración de redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers para archivos estáticos con cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para el service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Configuración de funciones (si se necesitan en el futuro)
[functions]
  directory = "netlify/functions"

# Configuración de plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Variables de entorno de ejemplo (se configuran en Netlify UI)
# VITE_SUPABASE_URL = "https://your-project.supabase.co"
# VITE_SUPABASE_ANON_KEY = "your-anon-key"