[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "22"
  # NPM_FLAGS eliminado (ya no es necesario con Vite)

# Configuración de redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers anti-cache para HTML/JS
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(self), microphone=(self), geolocation=(self)"

# Headers para archivos estáticos con cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para el service worker (anti-cache agresivo)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"

# Configuración de funciones (si se necesitan en el futuro)
[functions]
  directory = "netlify/functions"

# Configuración de plugins (opcional)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

# Variables de entorno de ejemplo (se configuran en Netlify UI)
# VITE_SUPABASE_URL = "https://your-project.supabase.co"
# VITE_SUPABASE_ANON_KEY = "your-anon-key"
