// Action types para el reducer de AppState
export const actionTypes = {
  SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
  SET_ORDERS: 'SET_ORDERS',
  ADD_ORDER: 'ADD_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  DELETE_ORDER: 'DELETE_ORDER',
  SHOW_ORDER_FORM: 'SHOW_ORDER_FORM',
  HIDE_ORDER_FORM: 'HIDE_ORDER_FORM',
  SET_EDITING_ORDER: 'SET_EDITING_ORDER',
  SHOW_ORDER_DETAILS: 'SHOW_ORDER_DETAILS',
  HIDE_ORDER_DETAILS: 'HIDE_ORDER_DETAILS',
  SET_SELECTED_ORDER: 'SET_SELECTED_ORDER',
  SHOW_DATA_MIGRATION: 'SHOW_DATA_MIGRATION',
  HIDE_DATA_MIGRATION: 'HIDE_DATA_MIGRATION',
  SET_LOADING: 'SET_LOADING',
  SET_FINANCIAL_VIEW: 'SET_FINANCIAL_VIEW'
}