name: CI / build

on:
  workflow_dispatch:  # solo corre cuando tú lo lanzas manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Dummies solo para CI (no producción)
      VITE_SUPABASE_URL: "https://example.supabase.co"
      VITE_SUPABASE_ANON_KEY: "test-anon-key"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci || npm i

      - name: Build
        run: npm run build
